name: Deploy MkDocs Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    uses: dyvenia/workflow-templates/.github/workflows/template_static_site_prepare_mkdocs.yml@main
    with:
      project_manager: rye
      static_site_branch: gh-pages
      mkdocs_config: mkdocs.yml
      site_dir: site
    secrets: inherit # pragma: allowlist secret
